"""add unique organization membership constraint

Revision ID: 1ad1a96548c3
Revises: 0b2b1ce8e510
Create Date: 2026-08-26 09:43:14.949176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad1a96548c3'
down_revision: Union[str, Sequence[str], None] = '0b2b1ce8e510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_organization_member', 'organization_members', ['organization_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organization_member', 'organization_members', type_='unique')
    # ### end Alembic commands ###
