"""Preserve conversations when customer is deleted

Revision ID: 5c0fb4b37ae5
Revises: 655395d193cb
Create Date: 2026-09-01 11:15:59.043480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0fb4b37ae5'
down_revision: Union[str, Sequence[str], None] = '655395d193cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('conversations_customer_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_customer_id_fkey'), 'conversations', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
